version: '3'

services:
    services:
        build: ./
        command: | 
            sh -c '
                python -m src1 &
                python -m src2 &
                sleep 100
            '
        expose: 
            - 8001
            - 8002
        environment:
            - PYTHONUNBUFFERED=1
    gateway:
        image: xmorse/apollo-federation-gateway
        ports:
            - 8000:80
        environment:
            CONFIG: |
                [
                    {
                        "name": "1",
                        "url": "http://services:8001/graphql"
                    },
                    {
                        "name": "2",
                        "url": "http://services:8002/graphql"
                    }
                ]